[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.build]
cmds = [
    "pip install -r SERVER_SIDE/requirements.txt",
    "cd CLIENT_SIDE && npm install && npm run build",
    "cd SERVER_SIDE && python manage.py collectstatic --noinput"
]

[phases.start]
cmds = ["gunicorn byfaith_project.wsgi:application --bind 0.0.0.0:8000"]
